package sn.modeltech.banky.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AgenceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgenceAllPropertiesEquals(Agence expected, Agence actual) {
        assertAgenceAutoGeneratedPropertiesEquals(expected, actual);
        assertAgenceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgenceAllUpdatablePropertiesEquals(Agence expected, Agence actual) {
        assertAgenceUpdatableFieldsEquals(expected, actual);
        assertAgenceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgenceAutoGeneratedPropertiesEquals(Agence expected, Agence actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgenceUpdatableFieldsEquals(Agence expected, Agence actual) {
        assertThat(expected)
            .as("Verify Agence relevant properties")
            .satisfies(e -> assertThat(e.getIdAgence()).as("check idAgence").isEqualTo(actual.getIdAgence()))
            .satisfies(e -> assertThat(e.getCodeAgence()).as("check codeAgence").isEqualTo(actual.getCodeAgence()))
            .satisfies(e -> assertThat(e.getNomAgence()).as("check nomAgence").isEqualTo(actual.getNomAgence()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgenceUpdatableRelationshipsEquals(Agence expected, Agence actual) {
        assertThat(expected)
            .as("Verify Agence relationships")
            .satisfies(e -> assertThat(e.getBanque()).as("check banque").isEqualTo(actual.getBanque()));
    }
}
