package sn.modeltech.banky.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CanalAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCanalAllPropertiesEquals(Canal expected, Canal actual) {
        assertCanalAutoGeneratedPropertiesEquals(expected, actual);
        assertCanalAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCanalAllUpdatablePropertiesEquals(Canal expected, Canal actual) {
        assertCanalUpdatableFieldsEquals(expected, actual);
        assertCanalUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCanalAutoGeneratedPropertiesEquals(Canal expected, Canal actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCanalUpdatableFieldsEquals(Canal expected, Canal actual) {
        assertThat(expected)
            .as("Verify Canal relevant properties")
            .satisfies(e -> assertThat(e.getIdCanal()).as("check idCanal").isEqualTo(actual.getIdCanal()))
            .satisfies(e -> assertThat(e.getLibelle()).as("check libelle").isEqualTo(actual.getLibelle()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCanalUpdatableRelationshipsEquals(Canal expected, Canal actual) {
        // empty method
    }
}
