package sn.modeltech.banky.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ContratAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContratAllPropertiesEquals(Contrat expected, Contrat actual) {
        assertContratAutoGeneratedPropertiesEquals(expected, actual);
        assertContratAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContratAllUpdatablePropertiesEquals(Contrat expected, Contrat actual) {
        assertContratUpdatableFieldsEquals(expected, actual);
        assertContratUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContratAutoGeneratedPropertiesEquals(Contrat expected, Contrat actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContratUpdatableFieldsEquals(Contrat expected, Contrat actual) {
        assertThat(expected)
            .as("Verify Contrat relevant properties")
            .satisfies(e -> assertThat(e.getIdContrat()).as("check idContrat").isEqualTo(actual.getIdContrat()))
            .satisfies(e -> assertThat(e.getDateValidite()).as("check dateValidite").isEqualTo(actual.getDateValidite()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContratUpdatableRelationshipsEquals(Contrat expected, Contrat actual) {
        assertThat(expected)
            .as("Verify Contrat relationships")
            .satisfies(e -> assertThat(e.getTypeContrat()).as("check typeContrat").isEqualTo(actual.getTypeContrat()));
    }
}
