package sn.modeltech.banky.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class JourFerierAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJourFerierAllPropertiesEquals(JourFerier expected, JourFerier actual) {
        assertJourFerierAutoGeneratedPropertiesEquals(expected, actual);
        assertJourFerierAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJourFerierAllUpdatablePropertiesEquals(JourFerier expected, JourFerier actual) {
        assertJourFerierUpdatableFieldsEquals(expected, actual);
        assertJourFerierUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJourFerierAutoGeneratedPropertiesEquals(JourFerier expected, JourFerier actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJourFerierUpdatableFieldsEquals(JourFerier expected, JourFerier actual) {
        assertThat(expected)
            .as("Verify JourFerier relevant properties")
            .satisfies(e -> assertThat(e.getIdJourFerie()).as("check idJourFerie").isEqualTo(actual.getIdJourFerie()))
            .satisfies(e -> assertThat(e.getLibelle()).as("check libelle").isEqualTo(actual.getLibelle()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJourFerierUpdatableRelationshipsEquals(JourFerier expected, JourFerier actual) {
        // empty method
    }
}
