package sn.modeltech.banky.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ParametrageGlobalAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParametrageGlobalAllPropertiesEquals(ParametrageGlobal expected, ParametrageGlobal actual) {
        assertParametrageGlobalAutoGeneratedPropertiesEquals(expected, actual);
        assertParametrageGlobalAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParametrageGlobalAllUpdatablePropertiesEquals(ParametrageGlobal expected, ParametrageGlobal actual) {
        assertParametrageGlobalUpdatableFieldsEquals(expected, actual);
        assertParametrageGlobalUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParametrageGlobalAutoGeneratedPropertiesEquals(ParametrageGlobal expected, ParametrageGlobal actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParametrageGlobalUpdatableFieldsEquals(ParametrageGlobal expected, ParametrageGlobal actual) {
        assertThat(expected)
            .as("Verify ParametrageGlobal relevant properties")
            .satisfies(e -> assertThat(e.getIdParamGlobal()).as("check idParamGlobal").isEqualTo(actual.getIdParamGlobal()))
            .satisfies(e -> assertThat(e.getCodeParam()).as("check codeParam").isEqualTo(actual.getCodeParam()))
            .satisfies(e -> assertThat(e.getTypeParam()).as("check typeParam").isEqualTo(actual.getTypeParam()))
            .satisfies(e -> assertThat(e.getValeur()).as("check valeur").isEqualTo(actual.getValeur()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParametrageGlobalUpdatableRelationshipsEquals(ParametrageGlobal expected, ParametrageGlobal actual) {
        // empty method
    }
}
