package sn.modeltech.banky.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TypeTransactionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeTransactionAllPropertiesEquals(TypeTransaction expected, TypeTransaction actual) {
        assertTypeTransactionAutoGeneratedPropertiesEquals(expected, actual);
        assertTypeTransactionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeTransactionAllUpdatablePropertiesEquals(TypeTransaction expected, TypeTransaction actual) {
        assertTypeTransactionUpdatableFieldsEquals(expected, actual);
        assertTypeTransactionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeTransactionAutoGeneratedPropertiesEquals(TypeTransaction expected, TypeTransaction actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeTransactionUpdatableFieldsEquals(TypeTransaction expected, TypeTransaction actual) {
        assertThat(expected)
            .as("Verify TypeTransaction relevant properties")
            .satisfies(e -> assertThat(e.getIdTypeTransaction()).as("check idTypeTransaction").isEqualTo(actual.getIdTypeTransaction()))
            .satisfies(e -> assertThat(e.getLibelle()).as("check libelle").isEqualTo(actual.getLibelle()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeTransactionUpdatableRelationshipsEquals(TypeTransaction expected, TypeTransaction actual) {
        // empty method
    }
}
