package sn.modeltech.banky.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TypeClientAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeClientAllPropertiesEquals(TypeClient expected, TypeClient actual) {
        assertTypeClientAutoGeneratedPropertiesEquals(expected, actual);
        assertTypeClientAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeClientAllUpdatablePropertiesEquals(TypeClient expected, TypeClient actual) {
        assertTypeClientUpdatableFieldsEquals(expected, actual);
        assertTypeClientUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeClientAutoGeneratedPropertiesEquals(TypeClient expected, TypeClient actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeClientUpdatableFieldsEquals(TypeClient expected, TypeClient actual) {
        assertThat(expected)
            .as("Verify TypeClient relevant properties")
            .satisfies(e -> assertThat(e.getIdTypeClient()).as("check idTypeClient").isEqualTo(actual.getIdTypeClient()))
            .satisfies(e -> assertThat(e.getLibelle()).as("check libelle").isEqualTo(actual.getLibelle()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeClientUpdatableRelationshipsEquals(TypeClient expected, TypeClient actual) {
        // empty method
    }
}
