package sn.modeltech.banky.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TypeContratAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeContratAllPropertiesEquals(TypeContrat expected, TypeContrat actual) {
        assertTypeContratAutoGeneratedPropertiesEquals(expected, actual);
        assertTypeContratAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeContratAllUpdatablePropertiesEquals(TypeContrat expected, TypeContrat actual) {
        assertTypeContratUpdatableFieldsEquals(expected, actual);
        assertTypeContratUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeContratAutoGeneratedPropertiesEquals(TypeContrat expected, TypeContrat actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeContratUpdatableFieldsEquals(TypeContrat expected, TypeContrat actual) {
        assertThat(expected)
            .as("Verify TypeContrat relevant properties")
            .satisfies(e -> assertThat(e.getIdTypeContrat()).as("check idTypeContrat").isEqualTo(actual.getIdTypeContrat()))
            .satisfies(e -> assertThat(e.getLibelle()).as("check libelle").isEqualTo(actual.getLibelle()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeContratUpdatableRelationshipsEquals(TypeContrat expected, TypeContrat actual) {
        // empty method
    }
}
