package sn.modeltech.banky.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VariableNotificationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVariableNotificationAllPropertiesEquals(VariableNotification expected, VariableNotification actual) {
        assertVariableNotificationAutoGeneratedPropertiesEquals(expected, actual);
        assertVariableNotificationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVariableNotificationAllUpdatablePropertiesEquals(VariableNotification expected, VariableNotification actual) {
        assertVariableNotificationUpdatableFieldsEquals(expected, actual);
        assertVariableNotificationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVariableNotificationAutoGeneratedPropertiesEquals(VariableNotification expected, VariableNotification actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVariableNotificationUpdatableFieldsEquals(VariableNotification expected, VariableNotification actual) {
        assertThat(expected)
            .as("Verify VariableNotification relevant properties")
            .satisfies(e -> assertThat(e.getIdVarNotification()).as("check idVarNotification").isEqualTo(actual.getIdVarNotification()))
            .satisfies(e -> assertThat(e.getCodeVariable()).as("check codeVariable").isEqualTo(actual.getCodeVariable()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVariableNotificationUpdatableRelationshipsEquals(VariableNotification expected, VariableNotification actual) {
        // empty method
    }
}
